CREATE TABLE CONTACT(
ID INT ,
EMAIL VARCHAR(20),
FNAME VARCHAR(20),
LNAME VARCHAR(20),
COMPANY VARCHAR(20),
ACTIVE_FLAG int,
OPT_OUT INT
);
INSERT INTO CONTACT VALUES(123,'a@a.com','kian','seth','abc',1,1),
(133,'b@b.com','neha','seth','abc',1,0),
(234,'c@c.com','puru','malik','cdf',0,0),
(342,'d@d.com','sid','maan','teg',1,0);
-- 1
SELECT * FROM CONTACT WHERE ACTIVE_FLAG=1;
-- 2
DELETE FROM CONTACT WHERE OPT_OUT=1;
-- 3
DELETE FROM CONTACT WHERE COMPANY='ABC';
-- 4
INSERT INTO CONTACT VALUES(658,'mili@gmail.com','mili',null,'DGH',1,1);
-- 5
SELECT COMPANY FROM CONTACT GROUP BY COMPANY HAVING COUNT(COMPANY)<=1;
-- 6
UPDATE CONTACT SET FNAME='niti' WHERE FNAME='mili';
SELECT * FROM CONTACT;