CREATE DATABASE CONSULTAION_THERAPY;
CREATE TABLE DOCTOR(
ID INT PRIMARY KEY NOT NULL,
NAME VARCHAR(20) NOT NULL,
SPECIALIZATION VARCHAR(30) NOT NULL,
ROOM INT ,
STUDIES VARCHAR(50) ,
SPEACIAL_REWARDS VARCHAR(30)
);
CREATE TABLE APPOINTMENTS(
APPOINTMENT_ID INT PRIMARY KEY NOT NULL,
PATIENT_ID INT NOT NULL,
DOCTOR_ID INT NOT NULL,
APPOINTMENT_DATE DATE,
EXAMINATIONROOM INT 
);
CREATE TABLE PATIENT(
ID INT PRIMARY KEY NOT NULL,
NAME VARCHAR(20) NOT NULL,
ADDRESS VARCHAR(39) NOT NULL,
PHONE INT ,
RELATED_DOCTOR VARCHAR(30) NOT NULL
);
CREATE TABLE REVIEWS(
DOCTER_ID INT NOT NULL,
RATING INT PRIMARY KEY ,
COMMENTS VARCHAR(50) 
);

